### ISSUE TITLE
S-type loadcell

### ISSUE THREAD

**Issue by ivajon** [Ltu-Bike-trailer/control-software#22]
We need to measure the voltage between the pairs of cables.

## TODO

- [ ] Amp or internal adc amp?
- [ ] PCB if external.
- [ ] Test with SAADC, talk with me for details on SAADC if needed.
- [ ] Convert to newton.
